//COMANDOS no WORKBENCH:

SELECT
*
FROM 'A PARTIR DE'
USE 'USE'
AND 'E'
OR 'OU'
CREATE DATABASE 'CRIAR UM BANCO DE DADOS'
DROP DATABASE 'DELETAR UM BANCO DE DADOS'
INSERT INTO ...
UPDATE ... SET
WHERE ...
DELETE FROM ...
ALTER TABLE ... 'ALTERAR TABELA'
ADD PRIMARY KEY()
ADD COLUMN()
LIMIT
AS ALIASES
BETWEEN

