CREATE TABLE tbCliente
(
CPF VARCHAR(11), 
NOME VARCHAR(100),
ENDEREÇO1 VARCHAR(150),
ENDEREÇO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
NASCIMENTO DATE,
IDADE TINYINT,
SEXO VARCHAR(1),
LIMITE_CRÉDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1)
)
